---
- name: install_source_list
  apt:
    deb: "https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb"
    state: "present"

- name: install_puppet
  apt:
    name: "puppet-agent"
    state: "present"
    update_cache: yes
    cache_valid_time: 3600

- name: add_master_ip_entry
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*puppet$' 
    line: "{{pa_master_addr}}  puppet" 
    state: "present"
  when: pa_master_addr is defined
  notify: restart puppet

- name: write puppet conf
  template:
    src:   puppet.conf.j2 
    dest:  /etc/puppetlabs/puppet/puppet.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx
  when: pa_master_fqdn is defined
  notify: restart puppet

- name: start_puppet
  service: 
    name: 'puppet.service' 
    enabled: 'yes'
    state: 'started'
