---
- name: puppet master 
  hosts: puppet_master
  become: yes
  roles:
    - role: puppet_master
      tags: ['vagrant','puppet']

- name: puppet agent
  hosts: puppet_agent
  become: yes
  roles:
    - role: puppet_agent
      tags: ['vagrant','agent']
