---
- name: lower_memory
  lineinfile:
    dest: "/etc/default/puppetserver"
    regexp: "^JAVA_ARGS=.*"
    state: "present"
    line: 'JAVA_ARGS="-Xms512m -Xmx1024m -XX:MaxPermSize=256m"'
  notify:
    - bounce puppet server

- name: add master ip entry
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*puppet$' 
    line: "{{pa_master_addr}}  puppet" 
    state: "present"
  when: pa_master_addr is defined

- name: write puppet conf
  template:
    src:   puppet.conf.j2 
    dest:  /etc/puppetlabs/puppet/puppet.conf
    owner: root
    group: root
    mode:  u=rwx,g=rx,o=rx
  when: pa_master_fqdn is defined
  notify:
    - bounce puppet server
